### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fadern** [elias123tre/passport_booker_se#1]
Hej,

Tack för ett bra script. Tyvärr smäller det ganska ofta på nedan.

`Python37>python c:\temp\main.py
Traceback (most recent call last):
  File "c:\temp\main.py", line 111, in <module>
    options[0], *options).grid(row=0, column=1)
IndexError: list index out of range`

Mina parametrar är.
personer: 3
tid: 22/06

OS: win 10
Python: 3.7

**Comment by eliasfloreteng** [comment]
Tack för feedbacken! Jag har gjort en hotfix så du får gärna utvärdera ifall det funkar bättre nu.

**Comment by fadern** [comment]
nu är den stabilare. Tackar
