### ISSUE TITLE
Bank-id....

### ISSUE THREAD

**Issue by umanonearth** [elias123tre/passport_booker_se#10]
Hello again, sorry to bother you again - now they have added bank-id to the equation... is there any possibility you have a look if you can do anything to make it work again like you did earlier?
Thinking I can do the same as before for my wife if I ask I take a photo of the screen, email her a picture and ask her to scan the  qr-code with her phone and then open her bank-id and accept and then your script can start searching every 25th second... or something like that. Would be highly appreciated if possible :) And thanks for your time.

**Comment by eliasfloreteng** [comment]
@umanonearth
I've updated the script and the download on the front page to work with BankID verification. You should be able to log in with BankID after starting the script and it will then search for times in the background automatically (until you get logged out by the system).

**Comment by umanonearth** [comment]
U r gr8!
Thanks a million!
