### ISSUE TITLE
Modify again?

### ISSUE THREAD

**Issue by umanonearth** [elias123tre/passport_booker_se#11]
Hello again this time and sorry to bother you again once again... - something has been added to the equation... So the script sort of dies... is there any possibility you can have yet another look if you can do anything to make it work again like you did earlier?
Thinking I can do the same as before for my nephews son if I take a photo of the screen, email him a picture and ask him to scan the qr-code with his phone and then open his bank-id and accept and then your script can start searching every 25th second... or something like that. Would be again and again and again highly appreciated if possible :) And thanks for your time. Again :))

**Comment by eliasfloreteng** [comment]
@umanonearth 
I published a new release containing a fix to this (v1.3.1). Apparently they added another step for entering whether to book passport, id or both. The script now pauses on that screen and resumes when you press next.
