### ISSUE TITLE
Not even a beginner... sorry

### ISSUE THREAD

**Issue by umanonearth** [elias123tre/passport_booker_se#2]
Hello,
sorry for disturbing and for asking, I know my way around a computer a bit, but know nothing about programming but am desperate for finding a time for passport... I have installed Python 3.10, I think my computer (win10) has Pip, I have installed Playwright (hopefully correct), I have installed Chromium, I have managed to open your file in VS Code and see the text/coding but I am not doing it correct because nothing more happens... becuause I lack the knowledge... 

Is there any possibility you can help me? 
The "how to" you have written is probably perfect for someone who knows programming but for me its just not enough.
Where should I open the script? In VS Code, in CMD, in Python? Or in Playwright or somewhere else? Maybe just a little more information and if possible - with links to where I can find a good easy way to install what I need.

Hope for the best
Skulle vara oerhört tacksam för hjälp med detta!
//Tobias

**Comment by eliasfloreteng** [comment]
Trevligt att du hör av dig med feedback!

I'm currently working on compiling the program into an executable that can be run without installing _anything_ and I hope to get it done today or during the weekend! I ofcourse agree that my instructions could be more beginner friendly, it doesn't even mention that the commands should be inputed to the terminal (cmd)

Tack för responsen!

**Comment by eliasfloreteng** [comment]
Regarding links to what you should install there isn't any, that's because you only need python, not vscode, not chromium, the necessary software is installed when running the commands in how-to. I will still update the instructions tough to be more clear!

**Comment by umanonearth** [comment]
Sounds excellent, thanks! Just so you know: I think your instructions are fantastic - I think you are excellent for sharing this! Its just that I am lacking some knowledge... :)

Now I tried again after your comment regarding only needing Python, so I tried to run 
pip install --upgrade pip
pip install playwright
playwright install chromium 
within python, first all of three lines together and then one by one but still no luck... Python says "Syntaxerror: Invalid syntax"  

Thanks again!

**Comment by umanonearth** [comment]
And now I did it in the CMD instead  - works a little bit better but get the following:

C:\Users\ADMINTobiasWolff>pip install --upgrade pip
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\site-packages (22.0.4)

C:\Users\ADMINTobiasWolff>pip install playwright
Collecting playwright
  Using cached playwright-1.20.1-py3-none-win_amd64.whl (27.9 MB)
Requirement already satisfied: greenlet==1.1.2 in c:\users\admintobiaswolff\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (1.1.2)
Requirement already satisfied: websockets==10.1 in c:\users\admintobiaswolff\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (10.1)
Requirement already satisfied: pyee==8.1.0 in c:\users\admintobiaswolff\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (8.1.0)
Installing collected packages: playwright
_ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINTobiasWolff\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\playwright\\driver\\package\\node_modules\\pixelmatch\\node_modules\\pngjs\\coverage\\lcov-report\\filter-parse.js.html'_

**Comment by eliasfloreteng** [comment]
I have updated the instructions, they should be a lot more clear now!

**Comment by eliasfloreteng** [comment]
@umanonearth I have now added a prebuilt binary for Windows that you can just download, click and run! See the [updated instructions](https://github.com/elias123tre/passport_booker_se#readme)

**Comment by umanonearth** [comment]
Hi again, and sorry, but the link you provided (Grey and green coloured) DOWNLOAD 1.0.0 goes to "404" within Github? So instead I tried the other option with the code, line by line, but doesnt get it to work. It says it cant find Playwright...

if you have the time, pls advise, would be greatful!

**Comment by eliasfloreteng** [comment]
I added the wrong download link but it is fixed now

**Comment by umanonearth** [comment]
Thanks a million, I was able to download the file when I had a look around and have managed to book me a time for passport! Thanks again!
