### ISSUE TITLE
error

### ISSUE THREAD

**Issue by skajagpangadig** [elias123tre/passport_booker_se#3]
C:\Program Files\Python310\python.exe: can't open file 'C:\\Users\\MALTE\\Downloads\\main.py': [Errno 2] No such file or directory

Får detta error vid sista steget. pls halp

**Comment by skajagpangadig** [comment]
försökte göra manual installtion men fick det error och downloaden är 404.

**Comment by skajagpangadig** [comment]
i had to specifiy where to launch the python code not jsut download map. friend helped me out. testing the script now.

**Comment by eliasfloreteng** [comment]
Det hade blivit ett fel med nedladdningslänken, det är åtgärdat nu och du borde kunna använda instructions for Windows
