### ISSUE TITLE
To many Calls - Redirected to secondary landing site

### ISSUE THREAD

**Issue by TherisaHaze** [elias123tre/passport_booker_se#4]
Hej.

Först, tack för ett färdigt verktyg för oss som inte riktigt vet vad vi gör när vi klistrar in kommandon i våra linuxburkar :)

Körde scriptet ett par gånger nu på kvällen och hamnar straxt på : https://reserv.polisen.se/for-manga-anrop/

Går det kanske att sänka antalet anrop per sekund för att motverka deras sätt att motverka att vanliga människor ska kunna boka en tid för pass :)

**Comment by erikrenberg** [comment]
Hur fort hamnar du på den där för-många-anrop-sidan? Polisen/deras leverantör kan ju tänkas ha ändrat något för att förhindra händiga scripts från att funka :/. 

Du skulle kunna prova editera rad 12 i main.py så att den kör mer sällan: Ändra till (30_000, 35_000) tex (motsvarar 30 till 35 sekunder).
```
# Random time between searches in milliseconds (min, max)
RANDOM_WAIT_RANGE = (15_000, 20_000)
```

**Comment by erikrenberg** [comment]
Jag körde programmet i helgen och i förmiddags utan de problem du beskriver. Men kanske de ändrat något sedan dess.

**Comment by TherisaHaze** [comment]
Tog max 1 minut innan den timade.

**Comment by eliasfloreteng** [comment]
Jag har också upptäckt det problemet, jag tror de har svartlistat vissa webbläsare (bland annat chromium, som skriptet använder) och omdirigerar därför direkt. Jag provade med firefox och det fungerade perfekt så jag ska uppdatera skriptet :)

**Comment by erikrenberg** [comment]
Det är nog bara en tidsfråga innan de kollar efter Firefox också då. Men då kanske @TherisaHaze lyckas få en tid först. 

Det kanske går att maskera browsern lite med lite slumpmässig user-agent (hur man nu gör sånt).

**Comment by eliasfloreteng** [comment]
Det går att implementera slumpad user-agent men tror inte det är värt för att de ändå kommer göra om systemet kommande vecka: https://www.expressen.se/dinapengar/sa-ska-polisen-stoppa-fulbokningen-av-pass/

**Comment by TherisaHaze** [comment]
Tack @erikrenberg för de uppmuntrande orden :) Passet går ut den 14:e och firman bjuder på weekend 12-16:e

**Comment by eliasfloreteng** [comment]
Men jag publicerar en hotfix tills dess, inom kort

**Comment by TherisaHaze** [comment]
För att förtydliga. Jag körde det i Windows-wrappern.

**Comment by eliasfloreteng** [comment]
Yes, jag kommer att uppdatera så att båda använder Firefox

**Comment by eliasfloreteng** [comment]
Ändringarna är publicerade som version [v1.1.0](https://github.com/elias123tre/passport_booker_se/releases/tag/v1.1.0). Nedladdningslänken i readme är också uppdaterad.

**Comment by TherisaHaze** [comment]
Tack som fan. Både F-secure och Windows Defender fick psykbryt, men väl 
i en VM så tuggar den nu på :)

/Hasse
