### ISSUE TITLE
scriptet crashar på rad 167 + fix

### ISSUE THREAD

**Issue by erikrenberg** [elias123tre/passport_booker_se#5]
Märkte när jag körde scriptet i helgen att det kraschar på rad 167 när en ledig tid hittas. Kanske för att sidan som visas innehåller tomrader på något sätt på just det passkontor jag söke på. Tyvärr debuggade jag inte så jag vet inte exakt när det händer.

Jag fixade problemet för att komma förbi det på följande sätt:

`if line and line[2] != ":"`

till

`if line and len(line)>2 and line[2] != ":"`

**Comment by eliasfloreteng** [comment]
Tack! Ska lägga in det!

**Comment by eliasfloreteng** [comment]
Fixet är nu pushat!
