### ISSUE TITLE
Kanske lägg till root.bell() efter rad 162 när en tid hittats

### ISSUE THREAD

**Issue by erikrenberg** [elias123tre/passport_booker_se#6]
Tack för ett bra script. Jag lyckades få tre tider till tre barn på tre dagar och på sätt sparades en onödig utflykt 40 mil enkel väg (för exfrun - inte för mig... :) ) till Haparanda där det av outgrundlig anledning fanns tider att boka! 

Men jag lyckades aldrig boka med dialogen som ska poppa upp från scriptet. Antingen såg jag den inte för att den låg bakom något fönster, eller så blev det något fel. Minns att jag bl a såg 'Hittad tid är inte längre tillgänglig' några gånger på konsollen.

Jag lade i alla fall en root.bell() i koden direkt den hittat en tid för att märka det, och sedan såg jag till att ha datorn nära, och vara på tårna, och när den pep till gick jag manuellt till polisens hemsida och bokade. På så sätt bokade jag tiderna. Tyvärr var jag inte helt fokuserad på att felsöka scriptet, mest på att boka passtider! :) 

```
                if date < last_date:
                    root.bell()
```

**Comment by eliasfloreteng** [comment]
Det finns redan en `root.bell()` på [rad 190](https://github.com/elias123tre/passport_booker_se/blob/main/main.py#L190) men jag kanske ska implementera att den plingar flera gåner (istället för bara en gång)?

**Comment by erikrenberg** [comment]
Ja, det var den raden jag såg och snodde :). Ja några fler pip skadar inte! (Jag körde faktiskt med winsound.Beep(1000, 300)  3 gånger i en liten loop för att verkligen pipa störigt (root.bell() var så mjäkigt) så jag skulle märka det men winsound är nog inte inte så  portabelt.

Men jag ville ha pipet så tidigt som möjligt, innan scriptet försöker klicka och vänta (som jag är osäker på om det ens fungerade  - men som sagt jag kan ha kollat för dåligt). (Och innan jag fixade felet med len(line)>2 som du pushade nyss så ville jag verkligen ha bell() tidigare för senare kraschade ju scriptet)

**Comment by eliasfloreteng** [comment]
Jag har nu pushat en ändring så att den plingar 3 gånger med 1.25 sekunder mellanrum, lagom för att höras lite bättre iallafall. Funderade också på winsound men vill fortfarande ha det cross-compatible.

**Comment by eliasfloreteng** [comment]
https://github.com/elias123tre/passport_booker_se/releases/tag/v1.1.1
