### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by mrAaaaaa** [elias123tre/passport_booker_se#7]
The booking system now has a reCaptcha that prevents the script from booking. Is there a solution for this?

**Comment by djking1** [comment]
Well, if its possbile for a pop up for the captcha to enter manually. Can you please fix the captcha thing? :) Should be an easy task. I will be really thankful, because I have tickets already and need a pass as soon as possible otherwise I will buy...

**Comment by eliasfloreteng** [comment]
Sorry if it took a couple of days, I hope it is fixed now, it pauses at the captcha for you to enter it then continues automatically! :)
