### ISSUE TITLE
blocked Firefox aswell?

### ISSUE THREAD

**Issue by umanonearth** [elias123tre/passport_booker_se#8]
Hello again, 

the script has been working but I tried to help my friend and now it seems not anymore. Tried it many times (the 1.1.1-version) and it fails. I run the .exe-file, it starts, I choose date and then it opens up a browser and the browser "fills" itself with date and so on but then the script dies - last "transmission" from the promt is "missing radioknappar" or something... Is there any possibilty u have a look? thanks a million so far anyways :)

**Comment by eliasfloreteng** [comment]
@umanonearth 
The problem has to do with a newly introduced captcha but the newest release should fix it!
