### ISSUE TITLE
"Hittar inte alla radioknappar"

### ISSUE THREAD

**Issue by bjornekelund** [elias123tre/passport_booker_se#9]
Kort glädje. Fungerade igår. Inte idag.

**Comment by djking1** [comment]
tråkigt.. hann inte ... hoppas att de kommer en uppdatering.. borde gå fort att uppdatera :)

**Comment by Fillson** [comment]
Kraschade några gånger för mig igår kväll men sen lyckades jag komma in och få en tid. Inte lyckats komma in på sidan idag dock.

**Comment by KingHippoSE** [comment]
Editera main.py och lägg till en sleep(10) före rad 91 så funkar det igen. Starta scriptet och fyll manuellt i captcha när du ser den, du har 10s på dig. Klicka inte på nästa, det sköter skriptet.

Resultatet ska bli detta:
    ppl_selector = page.locator('select[name="NumberOfPeople"]')
    ppl_selector.select_option(people.get())
    sleep(10)
    page.locator("text=Nästa").click()

**Comment by eliasfloreteng** [comment]
@bjornekelund @djking1 @Fillson @KingHippoSE 
Polisen har uppdaterat sitt system för att hindra bokningar som genomförs av skript såsom detta. Det är därför en captcha som behöver fyllas i. Den senaste versionen av skriptet löser detta (förhoppningsvis) så ni kan ladda ner den nya versionen så borde det funka!
